### ISSUE TITLE
boostrap.ini is corrupt 

### ISSUE THREAD

**Issue by JonathanAsbury-GMAIL** [Girilloid/libreoffice-file-converter#2]
On Windows 11
Perhaps they changed the format of what you're expecting?

**Comment by Girilloid** [comment]
Hi, @JonathanAsbury-GMAIL!
Thanks for your report. I'll check.

**Comment by Girilloid** [comment]
Hi, @JonathanAsbury-GMAIL!
The issue has been fixed in [v2.1.1](https://github.com/Girilloid/libreoffice-file-converter/releases/tag/v2.1.1)
