### ISSUE TITLE
Cannot set LibreOffice input filter (i.e. --infilter argument)

### ISSUE THREAD

**Issue by luca-costanzo** [Girilloid/libreoffice-file-converter#8]
Hello,

It seems impossible to set an input filter for the conversions, i.e. LibreOffice argument called **--infilter** .
This parameter is strictly needed for instance for the conversion of PDF files to other formats like DOCX (with value "writer_pdf_import"), otherwise, the input document is parsed as Draw document (instead of Writer) and the conversion does not succeed.

Example of a successful conversion command:
`soffice --headless --infilter="writer_pdf_import" --convert-to "docx" "document.pdf"`

Example of a broken conversion command:
`soffice --headless --convert-to "docx" "document.pdf"`

Thank you

**Comment by Girilloid** [comment]
Added in [v3.1.0](https://github.com/Girilloid/libreoffice-file-converter/releases/tag/v3.1.0)
