### ISSUE TITLE
LibreOffice args provided as array should not include double quotes

### ISSUE THREAD

**Issue by luca-costanzo** [Girilloid/libreoffice-file-converter#9]
Hello,

actually, LibreOffice args are being provided as an array, therefore they should not contain forced double quotes inside, even if they contain spaces, because they are already interpreted as single args in the array.

Therefore, the following lines of code should be modified:

1) from https://github.com/Girilloid/libreoffice-file-converter/blob/359b9455a6e4c71b4c36ebff4a6e72070d9644b2/src/helpers/libreoffice.ts#L55
to:
```typescript
const filterSegment = outputFilter && outputFilter.length > 0 ? `:${outputFilter}` : '';
```

2) from https://github.com/Girilloid/libreoffice-file-converter/blob/359b9455a6e4c71b4c36ebff4a6e72070d9644b2/src/helpers/libreoffice.ts#L60
to:
```typescript
args.push(`--infilter=${inputFilter}`);
```

Thank you very much

**Comment by Girilloid** [comment]
Thanks for your feedback. Fixed in [v3.3.1](https://github.com/Girilloid/libreoffice-file-converter/releases/tag/v3.1.1)
